"""create table

Revision ID: eb5cb3ca4d0b
Revises: 
Create Date: 2026-03-02 15:29:14.434641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'eb5cb3ca4d0b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('setorsampah',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tabungan_id', sa.Uuid(), nullable=False),
    sa.Column('jenis_sampah', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('berat', sa.Float(), nullable=False),
    sa.Column('harga', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tabungan',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nama', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('saldo', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tabungan')
    op.drop_table('setorsampah')
    # ### end Alembic commands ###
